- README.md
Due to use of Object.fromEntries like in `bin/index.js` line 38, the package need node.js v12 to be ran.
> docs: change node.js version

- i18n/english.js
- i18n/french.js
Fix typos and add consistency:
- Capitalize and remove punctuation from commands descriptions
- Add `...` at the end of running commands
- Add spaces before punctuation for `fr`, remove for `en`
- Removed `ui.popups.warnings.linkhere` as it is not used (should we keep it?)
> fix(i18n): typos and consistency

- i18n/english.js
- i18n/french.js
- public/css/popup.css
- public/css/reset.css
- public/js/popup.js
- views/index.html
Hi @fraxken  👋  
Very happy to submit you this pull request related the issue #48 ^^
I think we should consider the fact that each request to UNPKG should be cached. I'm not really opinionated about the way to do it. This is why I prefer to ask you first. I could propose something anyway.
A little preview:
> feat: add a preview of the incriminated code during mouse over

- i18n/english.js
- i18n/french.js
- src/warnings.js
Possible solution for the  issue #49
> Add missing i18n for global warnings

- public/js/utils.js
- src/commands/http.js
- src/http-server/bundle.js
- src/http-server/context.js
- src/http-server/index.js
- test/httpServer.spec.js
Hi 👋 
This issue resolves #91 
Added:
- `bundle/:pkgName/:version` endpoint
- `bundle/:pkgName/` endpoints
- functional tests
- add storage for HTTP server port
> Note: we could switch from `bundle/:pkgName/:version` to `bundle/:pkgName?version=:v` if you prefer.
> fix: move bundlephobia call in the backend

- public/js/components/package.info.js
- public/js/components/settings.js
- src/http-server/config.js
Fixing a bug with cached settings and default package menu to open. That fix make impossible for the left menu to not open when there is a cache mismatch.
> fix: use info as default instead of overview

- bin/index.js
- test/commands/summary.spec.js
I added a warning message on_commands("cwd | from | verify") by checking the environment variable NODE_SECURE_TOKEN
> Add a warning when NODE_SECURE_TOKEN is missing

- public/js/components/package.info.js
If the librairies use Node.js procotol imports, it will redirect to 404.
For instance: https://nodejs.org/dist/latest/docs/api/node:path.html instead of https://nodejs.org/dist/latest/docs/api/path.html
> fix: remove import protocol for doc redirection

- public/js/components/settings.js
- public/js/master.js
- test/httpServer.test.js
- workspaces/vis-network/src/dataset.js
- workspaces/vis-network/src/network.js
Fixes #221 
Also note `this.network.setOptions({ physics: false });`: this disable physics after initialization so now when we drag & move a node, the others one stay in place (it's much better and allow to move nodes as we want).
> feat: apply settings on save

- public/js/components/package/pannels/warnings.js
- public/js/components/settings.js
- public/js/master.js
> fix: left menu not updated

- public/css/views/home.css
- public/js/components/home.js
- public/js/master.js
- public/js/utils.js
- views/index.html
> feat: highlight suspicious packages

- public/components/package/pannels/warnings/code-fetcher.js
Highlight the whole `<tr>` when multi-line because highlight.js `span` can be opened/closed on differents lines.
With theses screens code snippet example, a `span` is opened line 22 & closed line 27 (by highlight.js), this why the line 27 is not fully highlighted
> fix(code-fetcher): improve multi-line code snippet

- i18n/english.js
- i18n/french.js
- public/components/views/home/report/report.js
- src/http-server/endpoints/report.js
- views/index.html
Allow to customize the theme for report export #352
> feat(interface) : Allow to customize the theme for report export

- public/components/views/search/search.css
- src/commands/scanner.js
- src/http-server/cache.js
- src/http-server/endpoints/data.js
- src/http-server/websocket/remove.js
- src/http-server/websocket/search.js
Update the cache when scanning a package via `nsecure from` or `nsecure cwd` (`cwd` will be improved in #442).
This PR also fixes the cache initialization: available payloads were saved in `list` instead of `older`, and the interface now correctly shows every package available (the `Packages available in the cache` section in the search page).
> fix: update cache when scanning via cli

- bin/index.js
- docs/cli/open.md
- i18n/english.js
- i18n/french.js
- public/components/navigation/navigation.js
- public/components/searchbar/searchbar.css
- public/core/search-nav.js
- public/main.js
- src/commands/http.js
- src/http-server/cache.js
- src/http-server/endpoints/data.js
- src/http-server/index.js
- src/http-server/websocket/search.js
- workspaces/vis-network/src/dataset.js
- workspaces/vis-network/src/utils.js
> feat: allow to open the interface with no initial package

- test/commands/summary.test.js
- test/process/summary-zero-dependencies.js
- test/process/summary.js
> test(cli/summary): fix broken tests

- public/components/wiki/wiki.css
This PR improve the wiki by fixing a little bug:
- Open the WIKI, flags section
- Select `⚔️ hasBannedFile`
-> The wiki shrinks because the content is too small to fill the max width
> feat(wiki): set fixed width

- package.json
- test/commands/summary.test.js
- test/helpers/cliCommandRunner.js
Closes #485 
This PR replaces the external strip-ansi dependency with the native Node.js method util.stripVTControlCharacters.
Changes :
- Removed strip-ansi from dependencies
- Updated summary.test.js to use util.stripVTControlCharacters
- Updated cliCommandRunner implementation to rely on the native method
Test :
All tests passed locally using npm run test.
> Replace strip-ansi with Node.js native util.stripVTControlCharacters

- package.json
- src/http-server/config.js
- test/config.test.js
> feat(Settings): disable experimental warnings by default

- i18n/english.js
- i18n/french.js
- public/components/package/package.html
- public/components/package/package.js
- public/components/package/pannels/overview/overview.js
- public/components/views/home/home.js
- public/components/views/settings/settings.js
- public/main.js
- src/http-server/config.js
- test/config.test.js
- test/httpServer.test.js
- views/index.html
> feat(interface): disable external requests

- bin/index.js
- docs/cli/auto.md
- docs/cli/cwd.md
- docs/cli/from.md
- i18n/english.js
- i18n/french.js
- package.json
- public/components/views/home/maintainers/maintainers.css
- public/components/views/home/maintainers/maintainers.js
- src/commands/parsers/contacts.js
- src/commands/scanner.js
- test/commands/parsers/contacts.test.js
- workspaces/vis-network/src/dataset.js
- workspaces/vis-network/test/dataset-payload.json
- workspaces/vis-network/test/dataset.test.js
> feat(contacts): highlight contacts

- i18n/english.js
- i18n/french.js
- package.json
- public/components/package/pannels/overview/overview.js
- public/components/views/home/home.html
- public/components/views/home/home.js
- workspaces/server/src/config.ts
> feat(interface): module types

- .github/workflows/size-satisfies.yml
- .github/workflows/vis-network.yml
should fix this PR: https://github.com/NodeSecure/cli/pull/528
> fix(ci): build all before workspace tests running

- package.json
- public/components/bundlephobia/bundlephobia.js
- public/components/package/package.html
- public/components/package/package.js
> refactor(bundlephobia): migrate from vanilla JS to Lit.js

- i18n/english.js
- i18n/french.js
- public/components/legend/legend.js
- public/components/locked-navigation/locked-navigation.js
- public/components/locker/locker.js
- public/components/package/package.js
- public/components/views/settings/settings.js
- public/core/events.js
- public/core/network-navigation.js
- public/main.js
- views/index.html
> feat(locked-navigation): add navigation arrows when lock mode is enabled
