public/css/style.css
public/js/master.js

(The const FLAGS is here to prepare the arrival of legend tooltips on hover on emojis)

feat: display flags in info section

---

bin/index.js
package-lock.json
package.json

chore: replace opn with open

---

public/css/style.css
public/js/master.js
views/index.html

Adding a search input with a focus, highlighter and information about the package selected

feat: Adding Search Input

---

public/js/master.js
views/index.html

fix: Wording

---

i18n/english.js
i18n/french.js
src/i18n.js

Implementation of french traduction

feat: french translation

---

bin/index.js

Hi 👋 
This PR is related to the issue https://github.com/ES-Community/nsecure/issues/43
Do you want to publish an alpha/beta, to make some manual tests?

fix(bin): use package version dynamically

---

FLAGS.md
flags/hasNativeCode.html
flags/manifest.json
index.d.ts
public/js/master.js
src/depWalker.js
src/dependency.class.js
test/__snapshots__/depWalker.js.snap
test/__snapshots__/httpServer.js.snap
views/index.html

PR to implement this feature https://github.com/ES-Community/nsecure/issues/47
Some parts may need some feedbacks before landing like:
- CONSTANTS in depWalker.js (if there is any ideas of missing extensions of packages).
- Emoji 🐲 (if you have any other ideas ^^).
etc..

Add a new flag to detect native addons/codes

---

src/depWalker.js
test/__snapshots__/depWalker.js.snap

feat: stdout global warnings

---

bin/index.js
i18n/english.js
i18n/french.js

👋 
Hi this PR resolves issue #60 
Here an overview of the result

feat: add summary command (draft)

---

index.d.ts
src/depWalker.js
test/__snapshots__/depWalker.js.snap

Hi mates ^^
This PR resolves issue #69.
I use the term `version` in the payload, let me know if you want something else like `nsecureVersion`.
👋

feat: add a version to nsecure JSON payload

---

package.json
test/commands/summary.spec.js
test/fixtures/result-test1.json

Tryin to work on a new feature (check version). I figured that test was broken on master but green on the CI.
TODO:

chore: fix ci

---

package-lock.json
package.json
src/commands/scanner.js
src/commands/vulnerability.js

Replacement of the @slimio/async-cli-spinner library by @topcli/spinner.

replacement of the @slimio/async-cli-spinner library by @topcli/spinner

---

public/css/components/package/header.css
public/js/components/package.info.js

👋 
This PR fixes #131 
@fraxken I didn't have so much inspiration, wdyt ? here is a preview

feat: 3rd party tools links (Snyk & Socket.dev)

---

.eslintrc
bin/index.js
package.json
src/commands/lang.js
src/commands/scanner.js
src/commands/scorecard.js
src/commands/summary.js
src/commands/vulnerability.js
src/http-server/endpoints/root.js
src/http-server/index.js
src/utils.js
test/commands/summary.spec.js
test/httpServer.spec.js

Manually bump `@nodesecure/i18n`, fixes breaking changes.

chore: bump i18n

---

package.json
public/css/components/package/navigation.css
public/js/components/package/pannels/scorecard.js
src/http-server/endpoints/ossf-scorecard.js
test/helpers/cliCommandRunner.js

feat: add color to scorecard menu

---

public/js/master.js

Allow to navigate between node with keyboard.
I'll create an issue for a v2 with positions (instead of based on node id for previous/next ones, use the node position (`x`, `y`) to move to the nearest node).

feat(network): keyboard navigation

---

public/css/views/home.css
public/js/components/home.js
public/js/utils.js
views/index.html

fix https://github.com/NodeSecure/cli/issues/258

refactor(home.view): rework authors section

---

public/css/components/package/header.css
public/js/components/package/header.js
views/index.html

refactor: revamp flags position & fix unicode segmentation bug

---

public/css/components/package/script.css
public/js/components/package/pannels/scripts.js

fix https://github.com/NodeSecure/cli/issues/257

feat: highlight suspicious scripts

---

bin/index.js
i18n/english.js
i18n/french.js
src/commands/http.js

fix https://github.com/NodeSecure/cli/issues/69
need review:
- i18n translation
- allowing deep merge in i18n package: https://github.com/NodeSecure/i18n/issues/112

feat: verify payload scanner version & implement local i18n

---

package.json
public/common/utils.js
public/components/package/pannels/overview/overview.js
public/components/views/home/maintainers/maintainers.js
workspaces/vis-network/src/dataset.js

related PR: https://github.com/NodeSecure/scanner/pull/201
https://github.com/NodeSecure/cli/assets/49707819/87440d4e-2ca0-43fc-a76b-3cb4e333b448

make npmAvatar primary src

---

README.md

Note: there is currently no shorter solution with shields.io

docs: add SLSA badge

---

src/cache.js
src/http-server/endpoints/data.js
src/http-server/websocket/commands/search.js
test/cache.test.js

Also remove useless async
Draft because npm downloads API is down atm
https://api.npmjs.org/downloads/point/last-week/fastify, https://www.npmjs.com/package/fastify

fix(http-server/data): initialize cache with available payloads

---

package.json

chore: update @nodesecure/scanner

---

public/components/legend/legend.js
public/components/views/settings/settings.js

Also sync the checkbox state in settings page

fix(interface): legend duplicates

---

workspaces/vis-network/src/network.js

feat(interface): enable network loader when switching package

---

public/components/package/pannels/overview/overview.js

feat(overview): make weekly downloads more readable
